apiVersion: v1
kind: Namespace
metadata:
  name: bar
  labels:
    environment-id: env_513fda21-018f-41b7-86c2-e297c069ab8e
    project-id: project_026a84f1-3c61-4245-bf19-35bb140f5fea
    project-name: Tesla
    environment-name: prod
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
